name: Machine Learning Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le référentiel
      uses: actions/checkout@v2

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si vous avez des dépendances à installer

    - name: Exécuter le script d'entraînement
      run: python bcancer.py

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Cloner le référentiel
      uses: actions/checkout@v2

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si vous avez des dépendances à installer

    - name: Exécuter le script de test
      run: python test.py
