name: Machine Learning Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Exécuter bcancer.py et créer l'artefact
      run: |
        python bcancer.py
        mv model.pkl $GITHUB_WORKSPACE/model.pkl
      working-directory: $GITHUB_WORKSPACE

    - name: Archiver l'artefact
      uses: actions/upload-artifact@v2
      with:
        name: model-artifact
        path: $GITHUB_WORKSPACE/model.pkl

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Télécharger l'artefact
      uses: actions/download-artifact@v2
      with:
        name: model-artifact
        path: $GITHUB_WORKSPACE/

    - name: Exécuter test.py
      run: |
        python test.py
